# Generated by Django 3.2 on 2021-04-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0005_alter_decision_admission_status"),
        ("authentication", "0003_alter_user_publish_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="attending_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Can't see your college? Make sure you've added a decision with an admit status.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attending_college",
                to="destinations.decision",
                verbose_name="College attending",
            ),
        ),
    ]
