# Generated by Django 3.2 on 2021-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="GPA",
            field=models.FloatField(blank=True, help_text="Weighted GPA", null=True),
        ),
    ]
