# Generated by Django 3.2.12 on 2022-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_alter_user_gpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
