# Generated by Django 3.2.18 on 2023-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0014_user_is_banned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="GPA",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Pre-senior year, weighted GPA",
                max_digits=4,
                null=True,
            ),
        ),
    ]
