# Generated by Django 3.2 on 2021-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="admitted",
            field=models.BooleanField(default=False),
        ),
    ]
