# Generated by Django 3.2 on 2021-04-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0003_alter_decision_admitted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="decision",
            old_name="admitted",
            new_name="admission_status",
        ),
    ]
