# Generated by Django 3.2 on 2021-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0004_rename_admitted_decision_admission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="admission_status",
            field=models.CharField(
                choices=[
                    ("ADMIT", "Admitted"),
                    ("WAITLIST", "Waitlisted"),
                    ("WAITLIST_ADMIT", "Waitlist-Admitted"),
                    ("WAITLIST_DENY", "Waitlist-Denied"),
                    ("DEFER", "Deferred"),
                    ("DEFER_ADMIT", "Deferred-Admitted"),
                    ("DEFER_DENY", "Deferred-Denied"),
                    ("DENY", "Denied"),
                ],
                max_length=20,
            ),
        ),
    ]
