# Generated by Django 3.2 on 2021-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0010_alter_college_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="testscore",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
