# Generated by Django 3.2.9 on 2021-11-09 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("destinations", "0011_auto_20210423_2357"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decision",
            options={"ordering": ["admission_status", "college"]},
        ),
    ]
