# Generated by Django 3.2.12 on 2022-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0013_alter_decision_admission_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="college",
            options={"ordering": ["name", "location"]},
        ),
        migrations.RemoveField(
            model_name="college",
            name="ceeb_code",
        ),
        migrations.AlterField(
            model_name="decision",
            name="decision_type",
            field=models.CharField(
                choices=[
                    ("ED", "Early Decision"),
                    ("ED2", "Early Decision 2"),
                    ("EA", "Early Action"),
                    ("EA2", "Early Action 2"),
                    ("PR", "Priority"),
                    ("RD", "Regular Decision"),
                    ("RL", "Rolling"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
